### ISSUE TITLE
Dimensionless E-field not reported

### ISSUE THREAD

**Issue by ohenrich** [ludwig-cf/ludwig#197]
Hi Kevin,

I think I encountered a runtime issue. For the attached input file (nematic LC, initialised in (1, 1, 0) direction) I expect a dimensionless E-field strength to be reported in the prologue, but it is always zero:

```
Dielectric anisotropy      =  4.1400000e+01
Dimensionless field e      =  0.0000000e+00
```

However, the field seems to be OK in Ludwig as I can observe a realignment of the director over a longer time along (1, 0, 0) for `electric_e0 0.01_0_0`.

Could you please point me into the right direction and I can fix it and submit a pull request.

Cheers,
O

[input_e0.txt](https://github.com/ludwig-cf/ludwig/files/9310568/input_e0.txt)

**Comment by kevinstratford** [comment]
Yes, I would say that's a bug, where the field strength is uninitialised at the point of the dimensionless field computation.

I will fix.

**Comment by kevinstratford** [comment]
I have a fix for this. I've rejigged the implementation of the external field in the LC sector (particularly the time dependent bit).

The underlying reason is a desire to get rid of the `physics_t` global object (one of the problems with
which is a tendency to miss initialisations as we see here).

You may just want to keep an eye on this, as it
looks like there were no tests for this bit of the
computation.

**Comment by kevinstratford** [comment]
Fixed in development branch.
