### ISSUE TITLE
gradient_s7_anchoring unable to process fluid site from colloid collisions

### ISSUE THREAD

**Issue by aaronpim** [ludwig-cf/ludwig#204]
Issue: The new f**d_gradient_calculation** scheme **s7_anchoring** has issues when **colloid_init** is set to **from_file**. The code produces the following error:

> Starting time step loop.
> Ludwig.exe: gradient_s7_anchoring.c:1045: grad_s7_boundary_c: Assertion `pc' failed.

This issue is not encountered when I set **colloid_init** is set to **input_one**. Commenting out the line 1045 of grad_s7_boundary_c and recompiling LUDWIG from scratch, results in the following error:

> Signal: Segmentation fault (11)
> Signal code: Address not mapped (1)
> Failing at address: 0x90

Are there additional values in the input or colloid_init file required for the gradient scheme to work? Or is this an error in how LUDWIG processes fluid sites of colloids generated from a file?

[Note: I have closed the previous thread where I initially found this issue as I had not identified the cause of the issue.]

**Comment by aaronpim** [comment]
Further testing shows that this issue is present when the variable **colloid_init** is set to **input_random**. The code successfully complied and was able to run for over 270 timesteps before encountering the same error as above. 

I believe this might be an issue when colloids collides with a wall, as in the small simulation that I ran the simulation terminated when a colloid collides with a boundary. to pass through the edge of a periodic boundary, and it also terminated when another colloid collided with one of the walls. I have attached the code that I used to test this issue.
[S7_Colloid_Test.zip](https://github.com/ludwig-cf/ludwig/files/9478046/S7_Colloid_Test.zip)

**Comment by ohenrich** [comment]
@aaronpim Thanks for the test case, which should be really helpful.
@kevinstratford Is it straightforward to check what's going on? It's unclear whether I will have time to look into this within the next 3 weeks.

**Comment by kevinstratford** [comment]
I will try to have a look in the next week.

**Comment by kevinstratford** [comment]
I've now fixed the proximate cause of these failures in the latest release.

One must be aware that if different solids are coming into close proximity, then the anchoring 
is going to be on slightly shaky ground. This is
because the surface normal becomes poorly defined at the corner of the "join". So one really wants to prevent close approach to keep 
clear fluid sites between the colloids/walls. (This is what we have done in the past.)

A couple of ways of doing this are suggested in
the documentation. See the  boundary/colloid lubrication correction section. Also can use a repulsive colloid/colloid interact to maintain distance.

**Comment by kevinstratford** [comment]
Anyone had a chance to have a look?

**Comment by aaronpim** [comment]
I have run multiple simulations with colloids colloiding with the boundaries (and eachother) and it works perfect. Thank you for fixing the issue.

**Comment by ohenrich** [comment]
Excellent. It's good to know this is fixed and less likely to occur.
