### ISSUE TITLE
Body force on fluid when colloids are present

### ISSUE THREAD

**Issue by kevinstratford** [ludwig-cf/ludwig#285]
If there is a body force on the fluid, that there should also be a proportional contribution to the body force on any colloid present. This is currently, not handled.

There should not be a sedimentation force (gravity) on the colloids at the same time.

This is going to supersede #279 where Oliver states:

This is the fix that you said should go with the rest of the current development. The error becomes apparent when a colloid is in large confinement (small duct). The results agree very well with M.E. Staben et al., Phys. Fluids 15, 1711 (2003).

**Comment by kevinstratford** [comment]
Just need to move the new test `serial-coll-cf1.inp` to d3q27 when the ellipsoid updates are finalised.

**Comment by kevinstratford** [comment]
This is now reconciled at #263

**Comment by yehaozju** [comment]
Hi, @kevinstratford

The tutorial said that it is not possible to have both an external gravitational force on the colloid (as via colloid_gravity) and a body force on the fluid at the same time.

However, is there a possible  alternative realization because I wanna study a heavier particle (larger density and with gravity) settling in a pressure driven flow.

**Comment by kevinstratford** [comment]
Could you open a new issue for this question please? I'll have a look.
