### ISSUE TITLE
Not constant concentration field when a colloid is moving

### ISSUE THREAD

**Issue by Scolymus** [ludwig-cf/ludwig#29]
Hi Kevin,

 I am not sure if this is still happening, since it was happening in older compiles. If you have a concentration field that is not uniformly 0, (eg. you can use the routine from pull #27 to do it) I have seen that if you calculate the average value of the concentration field in your box is not constant, but it is increasing slowly in a kind of staircase function. Have you ever seen this effect?

eg. run a simulation with a colloid with a constant force. Use symmetric free energy and init the field to a uniform value, like 0.5. Then calculate the average of the concentration field in all the box except the nodes occupied by the particle over time.

**Comment by kevinstratford** [comment]
This will be caused by the repeated covering a uncovering of fluid nodes as
a colloid moves across the lattice (even the volume of fluid is not actually
constant).

If there's a significant long-term drift in the actual fluid composition, then it's
clearly a problem, and I will have a look at eliminating it.

**Comment by kevinstratford** [comment]
Hi,
I've had a chance to look at this and it looks like there are two issues:

1. The initial order parameter should be set with a consistent mean value
phi_0. In what you have it looks like they are not consistent. So I have
included a slightly altered version of your initialisation which should appear
in the input as
```
phi_initialisation    uniform
phi0                  -0.1
```
where phi0 is the uniform value.

2. There was a bug in the composition replacement which should have occurred as particles moved (sorry!). I've fixed it so that the mean composition should remain unchanged.

These are patched in 0.8.16 in the master.

**Comment by kevinstratford** [comment]
I hope this part should now work ok.

**Comment by Scolymus** [comment]
Sorry @kevinstratford, but what does dphitot variable do in build_conservation_phi? Did you forget to assign that variable to any place? Because you are adding dphi to it but then you don't use it!

**Comment by kevinstratford** [comment]
Apologies, the dphitot should have been removed. It does nothing. I'm going to do a few more tests in other contexts...
